version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run test -- --coverage --watchAll=false
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes