version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run test -- --coverage --watchAll=false
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://${BUCKET_NAME}/
